name: aarnet_filesender
owner: galaxy-australia
homepage_url: https://filesender.aarnet.edu.au
remote_repository_url: https://github.com/usegalaxy-au/tools-au/tree/master/tools/aarnet_filesender
categories:
  - Data Export
type: unrestricted
description: Transfer files to AARNet's FileSender Service
long_description: Transfer files to AARNet's FileSender Service
exclude:
  - tool_test_output.html
  - tool_test_output.json